stages:
  - build
  - test
  - deploy
  - notify

build:
  stage: build
  image: golang:1.21
  script:
    - go run .
    - go build -o app .
  artifacts:
    paths:
      - app

test:
  stage: test
  image: golang:1.21
  script:
    - go test ./...

deploy:
  stage: deploy
  image: golang:1.21
  script:
    - echo "Deploying application..."
    # Add your actual deployment commands here, e.g.,
    # - scp app user@server:/path/to/deploy
    # - ssh user@server "systemctl restart myapp"
  only:
    - main

notify_slack:
  stage: notify
  image: alpine
  before_script:
    - apk add --no-cache curl jq  # Install curl and jq
  script:
    - ls -l  # List all files to check if notify_slack.sh exists
    - cat notify_slack.sh  # Show file content for verification
    - chmod +x notify_slack.sh
    - sh ./notify_slack.sh

  when: on_success  
