stages:
  - build
  - test

build:
  stage: build
  image: golang:1.21
  script:
    - go run .
    - go build -o app .
  artifacts:
    paths:
      - app

test:
  stage: test
  image: golang:1.21
  script:
    - go test ./...
