stages:
  - build
  - test
  - deploy
  - notify

build:
  stage: build
  image: golang:1.21
  script:
    - go run .
    - go build -o app .
  artifacts:
    paths:
      - app

test:
  stage: test
  image: golang:1.21
  script:
    - go test ./...

deploy:
  stage: deploy
  image: golang:1.21
  script:
    - echo "Deploying application..."
    # Add your actual deployment commands here, e.g.,
    # - scp app user@server:/path/to/deploy
    # - ssh user@server "systemctl restart myapp"
  only:
    - main

notify_slack:
  stage: notify
  image: alpine
  before_script:
    - apk add --no-cache curl
    - chmod +x notify_slack.sh  # Ensure it's executable
  script:
    - ./notify_slack.sh
  only:
    - main
  when: on_success
